/**
 * ONE-TIME generator: fetches real road geometry for each Chennai edge from the
 * free public OSRM demo server and bakes it into lib/city/edgePaths.ts as static
 * data. This keeps RULE 3 intact — at runtime ColdGrid has ZERO network
 * dependency and stays deterministic (RULE 4); OSRM is only a dev-time tool.
 *
 * Re-run with `node scripts/genEdgePaths.mjs` only if node coordinates or the
 * edge list in lib/city/chennai.ts change. Mirrors that data below.
 */

import { writeFile } from "node:fs/promises";

const NODES = {
  koyambedu: [80.194, 13.069],
  kasimedu: [80.297, 13.124],
  "aavin-madhavaram": [80.231, 13.148],
  "hub-perambur": [80.232, 13.112],
  "hub-guindy": [80.212, 13.008],
  "hub-ambattur": [80.162, 13.106],
  "t-nagar": [80.233, 13.041],
  mylapore: [80.269, 13.033],
  adyar: [80.257, 13.006],
  "anna-nagar": [80.21, 13.085],
  velachery: [80.221, 12.979],
};

const EDGES = [
  ["koyambedu_ambattur", "koyambedu", "hub-ambattur"],
  ["koyambedu_guindy", "koyambedu", "hub-guindy"],
  ["koyambedu_perambur", "koyambedu", "hub-perambur"],
  ["kasimedu_perambur", "kasimedu", "hub-perambur"],
  ["aavin_perambur", "aavin-madhavaram", "hub-perambur"],
  ["aavin_ambattur", "aavin-madhavaram", "hub-ambattur"],
  ["koyambedu_annanagar", "koyambedu", "anna-nagar"],
  ["koyambedu_tnagar", "koyambedu", "t-nagar"],
  ["kasimedu_mylapore_coastal", "kasimedu", "mylapore"],
  ["perambur_annanagar", "hub-perambur", "anna-nagar"],
  ["perambur_tnagar", "hub-perambur", "t-nagar"],
  ["perambur_mylapore", "hub-perambur", "mylapore"],
  ["guindy_tnagar", "hub-guindy", "t-nagar"],
  ["guindy_mylapore", "hub-guindy", "mylapore"],
  ["guindy_adyar_main", "hub-guindy", "adyar"],
  ["guindy_adyar_omr", "hub-guindy", "adyar"],
  ["guindy_velachery_main", "hub-guindy", "velachery"],
  ["guindy_velachery_taramani", "hub-guindy", "velachery"],
  ["ambattur_annanagar", "hub-ambattur", "anna-nagar"],
  ["perambur_guindy", "hub-perambur", "hub-guindy"],
  ["ambattur_perambur", "hub-ambattur", "hub-perambur"],
];

// Edges that should take a visibly different road than their sibling "main".
const ALTERNATE_IDS = new Set(["guindy_adyar_omr", "guindy_velachery_taramani"]);

const round5 = (n) => Math.round(n * 1e5) / 1e5;

function dedupe(coords) {
  const out = [];
  for (const c of coords) {
    const p = [round5(c[0]), round5(c[1])];
    const last = out[out.length - 1];
    if (!last || last[0] !== p[0] || last[1] !== p[1]) out.push(p);
  }
  return out;
}

async function fetchPath(id, fromId, toId) {
  const a = NODES[fromId];
  const b = NODES[toId];
  const alt = ALTERNATE_IDS.has(id);
  const url =
    `https://router.project-osrm.org/route/v1/driving/${a[0]},${a[1]};${b[0]},${b[1]}` +
    `?overview=full&geometries=geojson${alt ? "&alternatives=2" : ""}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${id}: HTTP ${res.status}`);
  const json = await res.json();
  if (json.code !== "Ok" || !json.routes?.length) throw new Error(`${id}: ${json.code}`);
  // For alternates take the most-different (last) route; else the fastest.
  const route = alt ? json.routes[json.routes.length - 1] : json.routes[0];
  const coords = dedupe(route.geometry.coordinates);
  return { coords, km: route.distance / 1000, n: coords.length };
}

async function main() {
  const result = {};
  for (const [id, from, to] of EDGES) {
    try {
      const { coords, km, n } = await fetchPath(id, from, to);
      result[id] = coords;
      console.log(`✓ ${id.padEnd(28)} ${n} pts, ${km.toFixed(2)} km`);
    } catch (e) {
      console.warn(`✗ ${id}: ${e.message} — falling back to straight line`);
      result[id] = [NODES[from].map(round5), NODES[to].map(round5)];
    }
    await new Promise((r) => setTimeout(r, 250)); // be gentle on the demo server
  }

  const body =
    `/**\n` +
    ` * AUTO-GENERATED by scripts/genEdgePaths.mjs — DO NOT EDIT BY HAND.\n` +
    ` *\n` +
    ` * Real road geometry [lon, lat] per Chennai edge, baked from OSRM so the\n` +
    ` * runtime has no network dependency (RULE 3) and stays deterministic (RULE 4).\n` +
    ` */\n\n` +
    `export const EDGE_PATHS: Record<string, [number, number][]> = ${JSON.stringify(
      result
    )};\n`;

  await writeFile(new URL("../lib/city/edgePaths.ts", import.meta.url), body);
  console.log(`\nWrote lib/city/edgePaths.ts (${EDGES.length} edges).`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
